import type { AppSettings, ProviderAccount, SubscriptionAccount } from "./types";

const observedAt = "2026-08-17T14:28:00-04:00";

export const demoProviders: ProviderAccount[] = [
  {
    id: "openai-primary",
    provider: "openai",
    name: "OpenAI API",
    type: "API Platform",
    status: "Live",
    source: "Official API",
    scope: "Organization",
    updatedLabel: "2 min ago",
    updatedAt: observedAt,
    officialUrl: "https://platform.openai.com/usage",
    credentialHint: "Admin key ·•••• 7K2Q",
    credentialKind: "admin",
    enabled: true,
    authenticationMode: "pastedSecret",
    credentialOwner: "dashboard",
    consentedAt: observedAt,
    lastValidatedAt: observedAt,
    history: [11, 17, 13, 22, 18, 26, 24],
    historyLabel: "Daily spend",
    historyBasis: "Provider history buckets",
    metrics: [
      { id: "openai-cost", label: "This month", value: "$18.42", numericValue: 18.42, metricKind: "cost", kind: "money", currency: "USD", scope: "Organization", window: "Aug 1–17", observedAt, source: "Official API" },
      { id: "openai-tokens", label: "Tokens", value: "4.2M", numericValue: 4200000, metricKind: "tokens", kind: "tokens", unit: "tokens", scope: "Organization", window: "Aug 1–17", observedAt, source: "Official API" },
      { id: "openai-requests", label: "Requests", value: "1,284", numericValue: 1284, metricKind: "requests", kind: "requests", unit: "requests", scope: "Organization", window: "Aug 1–17", observedAt, source: "Official API" },
    ],
  },
  {
    id: "deepseek-primary",
    provider: "deepseek",
    name: "DeepSeek API",
    type: "API Platform",
    status: "Live",
    source: "Official API",
    scope: "Account balance",
    updatedLabel: "3 min ago",
    updatedAt: "2026-08-17T14:27:00-04:00",
    officialUrl: "https://platform.deepseek.com/usage",
    credentialHint: "API key ·•••• 19AF",
    credentialKind: "api_key",
    enabled: true,
    authenticationMode: "pastedSecret",
    credentialOwner: "dashboard",
    consentedAt: observedAt,
    lastValidatedAt: observedAt,
    history: [78, 79, 80, 80, 81, 82, 82],
    historyLabel: "Total balance",
    historyBasis: "Local balance snapshots",
    metrics: [
      { id: "deepseek-total", label: "Total", value: "¥82.31", numericValue: 82.31, metricKind: "total_balance", kind: "money", currency: "CNY", scope: "Account balance", observedAt, source: "Official API" },
      { id: "deepseek-topup", label: "Topped-up", value: "¥70.00", numericValue: 70, metricKind: "topped_up_balance", kind: "money", currency: "CNY", scope: "Account balance", observedAt, source: "Official API" },
      { id: "deepseek-granted", label: "Granted", value: "¥12.31", numericValue: 12.31, metricKind: "granted_balance", kind: "money", currency: "CNY", scope: "Account balance", observedAt, source: "Official API" },
    ],
  },
  {
    id: "openrouter-primary",
    provider: "openrouter",
    name: "OpenRouter",
    type: "API Platform",
    status: "Stale",
    source: "Official API",
    scope: "Account credits",
    updatedLabel: "34 min ago",
    updatedAt: "2026-08-17T13:56:00-04:00",
    officialUrl: "https://openrouter.ai/activity",
    credentialHint: "Management key ·•••• D81C",
    credentialKind: "management",
    enabled: true,
    authenticationMode: "pastedSecret",
    credentialOwner: "dashboard",
    consentedAt: observedAt,
    lastValidatedAt: observedAt,
    history: [8, 12, 9, 14, 19, 23, 26],
    historyLabel: "Total usage",
    historyBasis: "Local account snapshots",
    metrics: [
      { id: "openrouter-credits", label: "Credits", value: "$100.50", numericValue: 100.5, metricKind: "account_credits", kind: "money", currency: "USD", scope: "Account credits", observedAt, source: "Official API" },
      { id: "openrouter-usage", label: "Usage", value: "$25.75", numericValue: 25.75, metricKind: "account_usage", kind: "money", currency: "USD", scope: "Account credits", window: "Lifetime", observedAt, source: "Official API" },
      { id: "openrouter-remaining", label: "Remaining", value: "$74.75", numericValue: 74.75, metricKind: "remaining_credits", kind: "money", currency: "USD", scope: "Account credits", window: "Calculated from official fields", observedAt, source: "Official API" },
    ],
  },
  {
    id: "google-ai-studio-primary",
    provider: "google-ai-studio",
    name: "Google AI Studio API",
    type: "API Platform",
    status: "Live",
    source: "Official API",
    scope: "Google Cloud project API access",
    updatedLabel: "5 min ago",
    updatedAt: observedAt,
    officialUrl: "https://aistudio.google.com/usage",
    credentialHint: "API key · Windows Credential Manager",
    credentialKind: "api_key",
    enabled: true,
    authenticationMode: "pastedSecret",
    credentialOwner: "dashboard",
    consentedAt: observedAt,
    lastValidatedAt: observedAt,
    history: [],
    historyLabel: "History",
    historyBasis: "No public usage history endpoint",
    diagnostic: "API key validation only. Project usage, spend and balance remain in Google AI Studio.",
    metrics: [
      { id: "google-models", label: "Models", value: "18", numericValue: 18, metricKind: "accessible_models", kind: "count", unit: "models", scope: "Google Cloud project API access", observedAt, source: "Official API" },
    ],
  },
];

export const demoSubscriptions: SubscriptionAccount[] = [
  {
    id: "chatgpt-plus",
    provider: "chatgpt-codex",
    name: "ChatGPT Plus",
    type: "Subscription",
    plan: "Codex quota",
    status: "Live",
    source: "CLI/OAuth",
    scope: "Codex only",
    updatedLabel: "8 min ago",
    updatedAt: observedAt,
    officialUrl: "https://chatgpt.com/#settings/Subscription",
    monthlyPrice: "$20 / month",
    renewalDate: "Renews Sep 3",
    credentialHint: "Local Codex app-server",
    credentialKind: "local_cli",
    enabled: true,
    authenticationMode: "sharedLocalSession",
    credentialOwner: "codex",
    identityLabel: "signed-in Codex account",
    consentedAt: observedAt,
    lastValidatedAt: observedAt,
    history: [69, 66, 64, 62, 60, 58, 56],
    historyLabel: "Codex quota remaining",
    historyBasis: "Local Codex quota snapshots",
    metrics: [
      { id: "codex-5h", label: "5-hour remaining", value: "58%", numericValue: 58, metricKind: "quota_5h", kind: "quota", unit: "percent_remaining", scope: "Codex only", window: "Rolling 5 hours", resetTime: "2h 18m", observedAt, source: "CLI/OAuth" },
      { id: "codex-weekly", label: "Weekly remaining", value: "39%", numericValue: 39, metricKind: "quota_weekly", kind: "quota", unit: "percent_remaining", scope: "Codex only", window: "Weekly", observedAt, source: "CLI/OAuth" },
    ],
  },
  {
    id: "google-ai-pro",
    provider: "google-gemini-cli",
    name: "Google AI Pro",
    type: "Subscription",
    plan: "Gemini CLI quota",
    status: "Experimental",
    source: "CLI/OAuth",
    scope: "Gemini CLI only",
    updatedLabel: "18 min ago",
    updatedAt: observedAt,
    officialUrl: "https://one.google.com/explore-plan/gemini-advanced",
    monthlyPrice: "$19.99 / month",
    renewalDate: "Renews Sep 12",
    credentialHint: "Local Gemini CLI OAuth",
    credentialKind: "local_oauth",
    enabled: true,
    authenticationMode: "localCliOauth",
    credentialOwner: "geminiCli",
    identityLabel: "signed-in Gemini CLI account",
    consentedAt: observedAt,
    lastValidatedAt: observedAt,
    history: [],
    historyLabel: "Gemini CLI quota",
    historyBasis: "Per-model quota snapshots",
    metrics: [
      { id: "gemini-quota", label: "gemini-pro remaining", value: "72%", numericValue: 72, metricKind: "gemini_quota_1", kind: "quota", unit: "percent_remaining", scope: "Gemini CLI · gemini-pro", window: "Current window", resetTime: "1h 12m", observedAt, source: "CLI/OAuth" },
    ],
  },
];

export const defaultSettings: AppSettings = {
  apiRefreshMinutes: 15,
  localRefreshMinutes: 30,
  startOnLogin: true,
  minimizeToTray: true,
  historyRetentionDays: 90,
};
